<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TestService" targetNamespace="definitionNS" xmlns="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:ns1="schema1NS" 
  xmlns:tns="element1NS"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 
 <message name="myMethodRequest">
     <part name="x" type="xsd:int"/>
     <part name="y" type="xsd:float"/>
 </message>
 <message name="empty"/>
 
 <portType name="PT">
     <operation name="myMethod">
         <input message="myMethodRequest"/>
         <output message="empty"/>
     </operation>
 </portType>

 <binding name="TestBinding">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="myMethod">
   <input>
    <soap:body use="encoded"/>
   </input>
   <output>
    <soap:body use="encoded"/>
   </output>
  </operation>
 </binding>
</definitions> 
